
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ACTUALIZAR BASE BUSCAR CADENA COLECCION COMA CON CORCHETE_DER CORCHETE_IZQ CREAR DIFERENTE DOCUMENTO DONDE DOS_PUNTOS ELIMINAR EN FALSO ID IGUAL_IGUAL INSERTAR LLAVE_DER LLAVE_IZQ MAYOR MAYOR_IGUAL MENOR MENOR_IGUAL NUMERO O PUNTO_COMA TODO USAR VERDADERO Yprograma : sentenciassentencias : sentencia PUNTO_COMA sentenciassentencias : sentencia PUNTO_COMAsentencia : crear_db\n| usar_db\n| crear_col\n| insertar\n| buscar\n| actualizar\n| eliminarcrear_db : CREAR BASE IDusar_db : USAR IDcrear_col : CREAR COLECCION IDinsertar : INSERTAR EN ID DOCUMENTO documentobuscar : BUSCAR EN ID TODObuscar : BUSCAR EN ID DONDE condicionesactualizar : ACTUALIZAR EN ID DONDE condiciones CON documentoeliminar : ELIMINAR EN ID DONDE condicionesdocumento : LLAVE_IZQ pares LLAVE_DERpares : par COMA parespares : parpar : CADENA DOS_PUNTOS valorvalor : CADENAvalor : NUMEROvalor : VERDADEROvalor : FALSOvalor : documentovalor : CORCHETE_IZQ lista CORCHETE_DERlista : valor COMA listalista : valorlista : condiciones : condicion Y condicionescondiciones : condicion O condicionescondiciones : condicioncondicion : CADENA operador valoroperador : IGUAL_IGUAL\n| DIFERENTE\n| MAYOR\n| MENOR\n| MAYOR_IGUAL\n| MENOR_IGUAL'
    
_lr_action_items = {'CREAR':([0,17,],[11,11,]),'USAR':([0,17,],[12,12,]),'INSERTAR':([0,17,],[13,13,]),'BUSCAR':([0,17,],[14,14,]),'ACTUALIZAR':([0,17,],[15,15,]),'ELIMINAR':([0,17,],[16,16,]),'$end':([1,2,17,25,],[0,-1,-3,-2,]),'PUNTO_COMA':([3,4,5,6,7,8,9,10,20,26,27,33,37,39,40,43,57,60,61,62,63,64,65,66,67,69,74,],[17,-4,-5,-6,-7,-8,-9,-10,-12,-11,-13,-15,-14,-16,-34,-18,-19,-32,-33,-23,-35,-24,-25,-26,-27,-17,-28,]),'BASE':([11,],[18,]),'COLECCION':([11,],[19,]),'ID':([12,18,19,21,22,23,24,],[20,26,27,28,29,30,31,]),'EN':([13,14,15,16,],[21,22,23,24,]),'DOCUMENTO':([28,],[32,]),'TODO':([29,],[33,]),'DONDE':([29,30,31,],[34,35,36,]),'LLAVE_IZQ':([32,49,50,51,52,53,54,55,56,59,68,75,],[38,38,-36,-37,-38,-39,-40,-41,38,38,38,38,]),'CADENA':([34,35,36,38,47,48,49,50,51,52,53,54,55,58,59,68,75,],[41,41,41,46,41,41,62,-36,-37,-38,-39,-40,-41,46,62,62,62,]),'Y':([40,57,62,63,64,65,66,67,74,],[47,-19,-23,-35,-24,-25,-26,-27,-28,]),'O':([40,57,62,63,64,65,66,67,74,],[48,-19,-23,-35,-24,-25,-26,-27,-28,]),'CON':([40,42,57,60,61,62,63,64,65,66,67,74,],[-34,56,-19,-32,-33,-23,-35,-24,-25,-26,-27,-28,]),'IGUAL_IGUAL':([41,],[50,]),'DIFERENTE':([41,],[51,]),'MAYOR':([41,],[52,]),'MENOR':([41,],[53,]),'MAYOR_IGUAL':([41,],[54,]),'MENOR_IGUAL':([41,],[55,]),'LLAVE_DER':([44,45,57,62,64,65,66,67,70,71,74,],[57,-21,-19,-23,-24,-25,-26,-27,-20,-22,-28,]),'COMA':([45,57,62,64,65,66,67,71,73,74,],[58,-19,-23,-24,-25,-26,-27,-22,75,-28,]),'DOS_PUNTOS':([46,],[59,]),'NUMERO':([49,50,51,52,53,54,55,59,68,75,],[64,-36,-37,-38,-39,-40,-41,64,64,64,]),'VERDADERO':([49,50,51,52,53,54,55,59,68,75,],[65,-36,-37,-38,-39,-40,-41,65,65,65,]),'FALSO':([49,50,51,52,53,54,55,59,68,75,],[66,-36,-37,-38,-39,-40,-41,66,66,66,]),'CORCHETE_IZQ':([49,50,51,52,53,54,55,59,68,75,],[68,-36,-37,-38,-39,-40,-41,68,68,68,]),'CORCHETE_DER':([57,62,64,65,66,67,68,72,73,74,75,76,],[-19,-23,-24,-25,-26,-27,-31,74,-30,-28,-31,-29,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'programa':([0,],[1,]),'sentencias':([0,17,],[2,25,]),'sentencia':([0,17,],[3,3,]),'crear_db':([0,17,],[4,4,]),'usar_db':([0,17,],[5,5,]),'crear_col':([0,17,],[6,6,]),'insertar':([0,17,],[7,7,]),'buscar':([0,17,],[8,8,]),'actualizar':([0,17,],[9,9,]),'eliminar':([0,17,],[10,10,]),'documento':([32,49,56,59,68,75,],[37,67,69,67,67,67,]),'condiciones':([34,35,36,47,48,],[39,42,43,60,61,]),'condicion':([34,35,36,47,48,],[40,40,40,40,40,]),'pares':([38,58,],[44,70,]),'par':([38,58,],[45,45,]),'operador':([41,],[49,]),'valor':([49,59,68,75,],[63,71,73,73,]),'lista':([68,75,],[72,76,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> programa","S'",1,None,None,None),
  ('programa -> sentencias','programa',1,'p_programa','parser_nosql.py',7),
  ('sentencias -> sentencia PUNTO_COMA sentencias','sentencias',3,'p_sentencias_mult','parser_nosql.py',11),
  ('sentencias -> sentencia PUNTO_COMA','sentencias',2,'p_sentencias_una','parser_nosql.py',15),
  ('sentencia -> crear_db','sentencia',1,'p_sentencia','parser_nosql.py',20),
  ('sentencia -> usar_db','sentencia',1,'p_sentencia','parser_nosql.py',21),
  ('sentencia -> crear_col','sentencia',1,'p_sentencia','parser_nosql.py',22),
  ('sentencia -> insertar','sentencia',1,'p_sentencia','parser_nosql.py',23),
  ('sentencia -> buscar','sentencia',1,'p_sentencia','parser_nosql.py',24),
  ('sentencia -> actualizar','sentencia',1,'p_sentencia','parser_nosql.py',25),
  ('sentencia -> eliminar','sentencia',1,'p_sentencia','parser_nosql.py',26),
  ('crear_db -> CREAR BASE ID','crear_db',3,'p_crear_db','parser_nosql.py',31),
  ('usar_db -> USAR ID','usar_db',2,'p_usar_db','parser_nosql.py',36),
  ('crear_col -> CREAR COLECCION ID','crear_col',3,'p_crear_col','parser_nosql.py',41),
  ('insertar -> INSERTAR EN ID DOCUMENTO documento','insertar',5,'p_insertar','parser_nosql.py',46),
  ('buscar -> BUSCAR EN ID TODO','buscar',4,'p_buscar_todo','parser_nosql.py',51),
  ('buscar -> BUSCAR EN ID DONDE condiciones','buscar',5,'p_buscar_filtro','parser_nosql.py',56),
  ('actualizar -> ACTUALIZAR EN ID DONDE condiciones CON documento','actualizar',7,'p_actualizar','parser_nosql.py',61),
  ('eliminar -> ELIMINAR EN ID DONDE condiciones','eliminar',5,'p_eliminar','parser_nosql.py',66),
  ('documento -> LLAVE_IZQ pares LLAVE_DER','documento',3,'p_documento','parser_nosql.py',71),
  ('pares -> par COMA pares','pares',3,'p_pares_mult','parser_nosql.py',75),
  ('pares -> par','pares',1,'p_pares_uno','parser_nosql.py',79),
  ('par -> CADENA DOS_PUNTOS valor','par',3,'p_par','parser_nosql.py',83),
  ('valor -> CADENA','valor',1,'p_valor_cadena','parser_nosql.py',88),
  ('valor -> NUMERO','valor',1,'p_valor_numero','parser_nosql.py',92),
  ('valor -> VERDADERO','valor',1,'p_valor_true','parser_nosql.py',96),
  ('valor -> FALSO','valor',1,'p_valor_false','parser_nosql.py',100),
  ('valor -> documento','valor',1,'p_valor_doc','parser_nosql.py',104),
  ('valor -> CORCHETE_IZQ lista CORCHETE_DER','valor',3,'p_valor_lista','parser_nosql.py',108),
  ('lista -> valor COMA lista','lista',3,'p_lista_mult','parser_nosql.py',112),
  ('lista -> valor','lista',1,'p_lista_uno','parser_nosql.py',116),
  ('lista -> <empty>','lista',0,'p_lista_vacia','parser_nosql.py',120),
  ('condiciones -> condicion Y condiciones','condiciones',3,'p_condiciones_y','parser_nosql.py',125),
  ('condiciones -> condicion O condiciones','condiciones',3,'p_condiciones_o','parser_nosql.py',129),
  ('condiciones -> condicion','condiciones',1,'p_condiciones_simple','parser_nosql.py',133),
  ('condicion -> CADENA operador valor','condicion',3,'p_condicion','parser_nosql.py',137),
  ('operador -> IGUAL_IGUAL','operador',1,'p_operador','parser_nosql.py',141),
  ('operador -> DIFERENTE','operador',1,'p_operador','parser_nosql.py',142),
  ('operador -> MAYOR','operador',1,'p_operador','parser_nosql.py',143),
  ('operador -> MENOR','operador',1,'p_operador','parser_nosql.py',144),
  ('operador -> MAYOR_IGUAL','operador',1,'p_operador','parser_nosql.py',145),
  ('operador -> MENOR_IGUAL','operador',1,'p_operador','parser_nosql.py',146),
]
